# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uP1FpT3uS-UoE4AJjVulnYEsmg9ZhwkO
"""

import numpy as np

# 1. Massiv yaratish
array_1d=np.array([1,2,3,4,5])
array_1d=np.array([[1,2,3],[4,5,6]])

# 2.Matimatik operatsiyalar
sum_array=np.sum(array_1d)
mean_array=np.mean(array_1d)
product_array=np.prod(array)

print("1D Massiv:",array_1d)
print("2D Massiv:\n",array_2d)
print("Massivlar yigindisi:",sum_array)
print("O'rtacha:"mean_array)